### ISSUE TITLE
Documentation: Decentralized Identity (Part 3/4): Derivation path from keychain to Wallet Address

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics#35]
### Description: Access each wallet through Derivation Path
Decentralized identity contains several wallets. Keychain access only gives us the address of the keychain and not each wallet. A derivation path from keychain to the wallet takes the user to the specific wallet in his keychain.

In this issue we  understand the concept of  Derived Keys and Derivation Path from Keychain and document the Decentralized identity 's key derivation path that takes user to the specific wallet.

![roadmap_decentralized identity_device_key drawio](https://user-images.githubusercontent.com/26814150/171781582-f03b9343-199e-4c04-964e-3833483fe9c3.png)

### Tasks
- [x] Understanding Derived Keys
- [x] Understanding Derivation Path
- [x] Documentation: Keychain to Derivation Path of Wallet
