### ISSUE TITLE
Documentation: Decentralized Identity (Part 4/4):  Device Key & Transactions from after access to keychain

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics#36]
### Description : Transactions from the wallet and role of Device key in Transactions
After accessing the specific wallet the transactions from that wallet is the part of the same chain. We look at

-  The structure of transaction in the wallet
- The role of device keys in the transaction
- Signatures  in the transactions
- Keys stored in the transaction
-  Validations in the transaction

Transactions from the wallet and role of Device key in Transactions
![decentralized_identity](https://user-images.githubusercontent.com/26814150/173040478-155e0a9d-d0cf-4dab-abaf-de342596f401.jpg)

### Tasks
- [x] Documentation: Transaction structure in Wallet
-  Keys stored in the Transaction
- Signature in the Transaction
- [x] Documentation: Device Signature in the Transaction
- [x] Validations of the Decentralized Identity Transaction

**Comment by lucy-sha512** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics/36?planning-poker) with ZenHub @internet-zero @nilesh-uniris @sauravkr-diat-ai
