### ISSUE TITLE
Prototyping DID with Python and Libsodium Part 3/3: Implementing DID

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics#45]
### Description
With python and libsodium library we prototype the Decentralized Identity management in 3 parts:

1. Implementing cryptography functions like : generating keys, signing , verification , Ecc cryptography and AES encryption.
2. Implementing structures for Keychain/Accessing Transactions
3. Implementing DID with 1 & 2

In this issue we focus on 3

### Tasks

- [x] Encrypting keychain address transaction with public key
- [x] Encrypting keychain transaction with public  key
- [x] Decrypting keychain address transaction with private key
- [x] Decrypting keychain transaction with private key
- [x] Encrypting keychain with AES  key
- [x] Decrypting keychain with AES key
- [x] Access the wallet
- [x] Accessing the wallet transaction
- [x] signing wallet transaction data
- [x] signing  transaction

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/biometrics/45?planning-poker) with ZenHub @lucy-sha512 @nilesh-uniris
