### ISSUE TITLE
DID W3C Standard (Part 2/3) : Implementing the DID document in Python

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics#47]
### Description
In Issue #46 we identified and mapped the components of w3c standard.
Here we try to implement the DID-document in the format of w3c standard.
To do this we have to implement the following:
1.  Methods
2. DID controllers - organisation/people who can change the cryptographic keys for the DID.
3. Data registries- for our case, its AE blockchain and the keychain  stores the identities
4.DID document- the transaction fetched from keychain or AE blockchain , the wallet transaction should be fetched in the format of DID-document of w3c standard having information about DID-methods, DID-identifiers, cryptographic public key
5. DID URL : These documents are invoked through URL

### Tasks

- [ ] Implementing DID controllers and its methods 
Methods for:

- [ ] methods for changing cryptographic keys
- [ ] initiating authentication process

- [ ] Implementing DID registries 
Methods for : 

- [ ] Fetching transactions from AE blockchain

- [ ] Fetching key chain from AE blockchain

- [ ] Fetching wallet from AE blockchain

- [ ] Representing the output in w3c standard using JSON.

**Comment by lucy-sha512** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics/47?planning-poker) with ZenHub @internet-zero @nilesh-uniris

**Comment by lucy-sha512** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics/47?planning-poker) with ZenHub @samuel-uniris
