### ISSUE TITLE
Key generation using with User Input

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics#49]
### Description
The goal of this issue is to develop a standalone application  using C for generating ECC keys with user input.
The approach is as follows
Implementing ECC key generation using secp256 curve and edd curve. In secp256 we select a generator G and a  random number. The random number is the secret key sourced from user input.

### Tasks

- [x] Define methods to get the ECC curve / Edd curve parameters
- [x] Define methods for EC arithmetic
- [x] Private key generation  x with user input
- [x] Public key generation PK=G.x

**Comment by lucy-sha512** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics/49?planning-poker) with Zenhub @internet-zero @nilesh-uniris

**Comment by internet-zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics/49?planning-poker) with Zenhub @samuel-uniris
